# Generated by Django 5.0.4 on 2024-04-26 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userresetpassword'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userresetpassword',
            table='users_user_reset_password',
        ),
    ]
