# Generated by Django 5.0.4 on 2024-04-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresetpassword',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
