# Generated by Django 5.0.4 on 2024-06-24 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Frequency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=255)),
                ("frequency", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="SearchGuest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("search", models.TextField()),
                ("word", models.CharField(max_length=255, null=True)),
                ("exist", models.BooleanField(default=False)),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "api_search_guest",
            },
        ),
        migrations.CreateModel(
            name="Dictionary",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("word", models.CharField(max_length=255)),
                ("translation", models.CharField(max_length=255)),
                ("phonetic", models.CharField(max_length=255, null=True)),
                ("heteronyms", models.BooleanField(default=False)),
                ("pos", models.CharField(max_length=30, null=True)),
                ("sentences", models.TextField(null=True)),
                ("associate", models.TextField(null=True)),
                ("classification", models.TextField(null=True)),
                (
                    "auther",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("deleted", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="DictionaryVersion",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "dictionary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.dictionary"
                    ),
                ),
                ("word", models.CharField(max_length=255)),
                ("phonetic", models.CharField(max_length=255, null=True)),
                ("heteronyms", models.BooleanField(default=False)),
                ("pos", models.CharField(max_length=30, null=True)),
                ("translation", models.CharField(max_length=255)),
                ("sentences", models.TextField(null=True)),
                ("associate", models.TextField(null=True)),
                ("classification", models.TextField(null=True)),
                (
                    "auther",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("date", models.DateTimeField(blank=True, null=True)),    
            ],
            options={
                "db_table": "api_dictionary_version",
            },
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dictionary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.dictionary"
                    ),
                ),
                ("word", models.CharField(max_length=255)),
                ("quiz", models.TextField()),
                (
                    "auther",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("deleted", models.BooleanField(default=False)),  
            ],
        ),
        migrations.CreateModel(
            name="QuizVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dictionary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.dictionary"
                    ),
                ),
                ("word", models.CharField(max_length=255)),
                ("quiz", models.TextField()),
                (
                    "auther",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("date", models.DateTimeField(blank=True, null=True)), 
            ],
            options={
                "db_table": "api_quiz_version",
            },
        ),
        migrations.CreateModel(
            name="SearchWords",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("search", models.TextField()),
                ("word", models.CharField(max_length=255, null=True)),
                ("exist", models.BooleanField(default=False)),
                ("date", models.DateTimeField(auto_now_add=True)), 
            ],
            options={
                "db_table": "api_search_words",
            },
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dictionary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.dictionary"
                    ),
                ),
                ("word", models.CharField(max_length=255)),
                ("correct", models.IntegerField(default=0)),
                ("trials", models.IntegerField(default=0)),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "unique_together": {("user", "dictionary")},
            },
        ),
        migrations.CreateModel(
            name="SearchWord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dictionary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.dictionary"
                    ),
                ),
                ("count", models.IntegerField(default=1)),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "api_search_word",
                "unique_together": {("user", "dictionary")},
            },
        ),
    ]
