# Generated by Django 5.0.4 on 2024-06-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dictionary",
            name="heteronyms",
            field=models.BooleanField(default=False),
        ),
    ]
