# Generated by Django 5.0.4 on 2024-06-10 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchword",
            name="count",
            field=models.IntegerField(default=1),
        ),
    ]
