# Generated by Django 5.0.4 on 2024-07-04 08:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dictionary",
            name="associate",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dictionary",
            name="classification",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dictionary",
            name="phonetic",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="dictionary",
            name="sentences",
            field=models.TextField(blank=True, null=True),
        ),
    ]
