# Generated by Django 5.0.4 on 2024-07-04 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_dictionary_associate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dictionaryversion",
            name="associate",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dictionaryversion",
            name="classification",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dictionaryversion",
            name="phonetic",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="dictionaryversion",
            name="sentences",
            field=models.TextField(blank=True, null=True),
        ),
    ]
