# Generated by Django 5.0.4 on 2024-06-06 05:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_dictionary_heteronyms"),
    ]

    operations = [
        migrations.AddField(
            model_name="search",
            name="word",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
