# Generated by Django 5.0.4 on 2024-06-10 13:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_searchword_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="searchword",
            name="wordid",
        ),
    ]
