# Generated by Django 5.0.4 on 2024-06-06 05:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_search_word"),
    ]

    operations = [
        migrations.AddField(
            model_name="search",
            name="exist",
            field=models.BooleanField(default=False),
        ),
    ]
