# Generated by Django 5.0.4 on 2024-06-10 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_remove_searchword_wordid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="searchword",
            name="word",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.dictionary"
            ),
        ),
    ]
