# Generated by Django 5.0.4 on 2024-06-10 13:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_alter_searchword_word"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="searchword",
            unique_together={("user", "word")},
        ),
    ]
