from .answer import answer
from .associate import associate
from .dictionarylist import dictionarylist
from .history import history
from .openedit import openedit
from .quiz import quiz
from .search import search
from .word import word
from .words import words